stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "Building the application..."
    - chmod +x app/ci/*
    - app/ci/build.sh
    - sleep 60
