stages:
  - build
  - deploy

build_and_test_job:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - chmod +x app/ci/*
  script:
    - echo "Building and testing the application..."
    - app/ci/build.sh
  sleep: 10
  only:
    - master

deploy_job:
  stage: deploy
  image: python:3.10
  before_script:
    - pip install ansible
    - chmod +x ansible/deploy.sh
    - mkdir .ssh && echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 .ssh/id_rsa
    - eval $(ssh-agent -s)
    - ssh-add ~/.ssh/id_rsa
  script:
    - cd ansible
    - |
      ansible-playbook -i inventory.ini playbook.yml \
        --extra-vars "ssh_user=$SSH_USER ssh_port=$SSH_PORT sudo_pass$SUDO_PASSWORD"
