all:
  children:
    task10:
      hosts:
        server1:
          ansible_host: "{{ ssh_host }}"
          ansible_user: "{{ ssh_user }}"
          ansible_port: "{{ ssh_port }}"
          ansible_sudo_pass: "{{ sudo_pass }}"
          ansible_ssh_private_key: "/root/.ssh/id_rsa"
          ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
